dataset:
  name: 'CIFAR10'
  batch_size: 32
  img_size: 32
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
model:
  name: 'GAN'
  latent_dim: 10
  strides: [1,2,2,2]
  kernels: [3,3,3,3]
  nb_channels: [64, 128, 128, 256]
  dropout: 0.2
  conditionnal: False
optimization:
  lr_discriminator: 0.0002
  lr_generator: 0.0002
  epochs: 20
  beta_1: 0.5
  beta_2: 0.999
