dataset:
  name: 'MNIST'
  batch_size: 256
  img_size: 28
  mean: 0.5
  std: 0.5
model:
  name: 'GAN'
  latent_dim: 100
  strides: [2,2]
  kernels: [3,3]
  nb_channels: [64,128]
  dropout: 0.4
optimization:
  lr_discriminator: 0.0002
  lr_generator: 0.0002
  epochs: 20
  beta_1: 0.5
  beta_2: 0.999
