dataset:
  name: 'MNIST'
  batch_size: 256
  img_size: 28
  mean: 0.5
  std: 0.5
model:
  name: 'MultiStage_VAE'
  encoder_kernels: [7,3]
  encoder_strides: [2,2]
  encoder_size_blocks: 1
  avgpool: False
  maxpool_stride: 0
  encoder_channels: [16,32]
  latent_dim: 5
  decoder_channels: [32,16]
  decoder_nb_blockconvs: 1
  size_second_stage: 2
  conditionnal: False
optimization:
  lr: 0.0005
  kl_weight: 1
  criterion: 'bce'
  reduction: 'sum'
  epochs: 20