dataset:
  name: 'MNIST'
  batch_size: 256
  img_size: 28
  mean: 0.5
  std: 0.5
model:
  name: 'MultiStage_VAE'
  encoder_kernels: [7,3,3]
  encoder_strides: [2,2,2]
  encoder_size_blocks: 1
  avgpool: False
  maxpool_stride: 0
  encoder_channels: [16,32,64]
  latent_dim: 2
  decoder_channels: [64,32,16]
  decoder_nb_blockconvs: 0
  size_second_stage: 3
  conditionnal: False
optimization:
  lr: 0.001
  kl_weight:  1
  criterion: 'bce'
  reduction: 'sum'
  epochs: 50
  weight_decay: 0
  beta_1: 0.5