dataset:
    name: 'MNIST'
    batch_size: 256
    img_size: 28
    mean: 0.5
    std: 0.5
model:
    name: StyleGAN
    latent_dim: 160
    start_channel: 64
    nb_blocks_discr: 2
    nb_layers_mapping: 4
    init_channel: 128
    start_size: 7
optimization:
    lr_generator: 0.001
    lr_discriminator: 0.001
    epochs: 20
    gen_beta_1: 0.1
    discr_beta_1: 0