dataset:
  name: 'colorMNIST'
  batch_size: 64
  img_size: 28
  mean: 0.5
  std: 0.5
model:
  name: 'VAE_3D'
  img_channels: 3
  img_size: 28
  encoder_kernels: [3,3,3]
  encoder_strides: [2,2,2]
  #encoder_pad: [1,1,1]
  encoder_channels: [16,32,64]
  encoder_activation: 'leaky_relu'
  encoder_mlp_dims: [128,6]
  encoder_mlp_activation: 'leaky_relu'
  decoder_activation: 'leaky_relu'
  decoder_mlp_activation: 'leaky_relu'
  conditionnal: False
  nb_classes: 10
optimization:
  lr: 0.0002
  kl_weight:  0.00001
  criterion: 'bce'
  reduction: 'mean'
  epochs: 10
  weight_decay: 0.00001

