dataset:
  name: 'CIFAR10'
  batch_size: 256
  img_size: 32
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
model:
  name: 'VAE_3D'
  encoder_kernels: [7,3,3]
  encoder_strides: [2,2,2]
  encoder_channels: [16,32,64]
  encoder_activation: 'leaky_relu'
  encoder_mlp_dims: [128,100]
  encoder_mlp_activation: 'leaky_relu'
  decoder_activation: 'leaky_relu'
  decoder_mlp_activation: 'leaky_relu'
  conditionnal: False
optimization:
  lr: 0.0005
  kl_weight:  0.1
  criterion: 'bce'
  reduction: 'sum'
  epochs: 10
  weight_decay: 0.00001
