dataset:
  name: 'MNIST'
  batch_size: 64
  img_size: 32
  mean: 0.5
  std: 0.5
model:
  name: 'VAE_complex'
  img_channels: 1
  img_size: 28
  encoder_kernels: [7,3]
  encoder_strides: [2,2]
  maxpool_stride: 0
  avgpool: False
  encoder_size_blocks: 1
  encoder_channels: [32,64]
  latent_dim: 5
  decoder_channels: [64,32]
  decoder_nb_blockconvs: 1
  conditionnal: False
optimization:
  lr: 0.001
  kl_weight:  1
  criterion: 'bce'
  reduction: 'sum'
  epochs: 20
  weight_decay: 0
