dataset:
  name: 'CIFAR10'
  batch_size: 256
  img_size: 32
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
model:
  name: 'VQ_VAE'
  encoder_kernels: [3,3,3,3,3]
  encoder_strides: [2,2,2,1,1]
  encoder_channels: [32,64,128,32,32]
  encoder_activation: 'leaky_relu'
  decoder_activation: 'leaky_relu'
  conditionnal: False
  latent_dim: 64
  size_codebook: 512
optimization:
  lr: 0.001
  commitment_weight: 0.25
  criterion: 'mse'
  epochs: 40
  weight_decay: 0
latent_generator:
  model:
    name: PixelCNN
    nb_layers: 12
    channel_dim: 32
  optimization:
    criterion: 'cross_entropy'
    epochs: 10
    lr: 0.005
    
