dataset:
  name: 'MNIST'
  batch_size: 256
  img_size: 28
  mean: 0.5
  std: 0.5
model:
  name: 'VQ_VAE'
  encoder_kernels: [3,3,3,2]
  encoder_strides: [2,2,1,1]
  encoder_channels: [16,32,64,16]
  encoder_activation: 'leaky_relu'
  decoder_activation: 'leaky_relu'
  conditionnal: False
  latent_dim: 4
  size_codebook: 5
optimization:
  lr: 0.005
  commitment_weight: 0.2
  criterion: 'mse'
  epochs: 20
  weight_decay: 0
latent_generator:
  model:
    name: PixelCNN
    nb_layers: 12
    channel_dim: 32
  optimization:
    criterion: 'cross_entropy'
    epochs: 10
    lr: 0.005
    
